version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "anti-resume"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12nqj0x2jb92"
s3_prefix = "anti-resume"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
